'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApp9.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3f9fed05f53b28aac803243d71a57055() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3f9fed05f53b28aac803243d71a57055", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _58PIC9w58PIC58PICjcp2zDIKp1eb_PIC2018() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("58PIC9w58PIC58PICjcp2zDIKp1eb_PIC2018", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _58PIC9w58PIC58PICjcp2zDIKp1eb_PIC20181() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("58PIC9w58PIC58PICjcp2zDIKp1eb_PIC20181", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8f2bf1e1a7c933ca713c8e3dd5f14e28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8f2bf1e1a7c933ca713c8e3dd5f14e28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94511253_714940765909200_7865515287250993152_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94511253_714940765909200_7865515287250993152_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94521590_1515560075286793_8460356042860003328_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94521590_1515560075286793_8460356042860003328_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94560888_1128538257504694_4337063095101816832_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94560888_1128538257504694_4337063095101816832_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94566666_3228432930520750_3453754623448317952_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94566666_3228432930520750_3453754623448317952_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94569260_1131041950571473_824528601507430400_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94569260_1131041950571473_824528601507430400_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94644736_747191376102452_7753191399855489024_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94644736_747191376102452_7753191399855489024_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94750895_589971984949389_3402599999584862208_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94750895_589971984949389_3402599999584862208_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94779970_560004817987924_8780451116388188160_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94779970_560004817987924_8780451116388188160_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94780335_253844709077865_8107266906009894912_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94780335_253844709077865_8107266906009894912_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94883606_270238394171647_2786127323361968128_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94883606_270238394171647_2786127323361968128_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94887665_325266465119171_2364921641579839488_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94887665_325266465119171_2364921641579839488_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94888412_536641267242212_6730596842439966720_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94888412_536641267242212_6730596842439966720_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94908322_524950948182076_658540145720426496_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94908322_524950948182076_658540145720426496_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _94911583_741094223295444_6120779346891243520_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94911583_741094223295444_6120779346891243520_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _95019517_1412741218905779_5049060276394000384_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("95019517_1412741218905779_5049060276394000384_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _95031230_1080007559040068_3845212601529139200_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("95031230_1080007559040068_3845212601529139200_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _95286990_246980066712741_7330832695448043520_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("95286990_246980066712741_7330832695448043520_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _95554383_165213804828217_488573871612493824_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("95554383_165213804828217_488573871612493824_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property a84bc338551f18242dc221a1be4130c4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a84bc338551f18242dc221a1be4130c4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ESgW4M_XQAAWYx9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ESgW4M_XQAAWYx9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ESgW4M_XQAAWYx9__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ESgW4M_XQAAWYx9 (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ff78a28155b93cdd420d056fdf9a9ff2__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ff78a28155b93cdd420d056fdf9a9ff2 (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kisspng_coffee_cup_cafe_tea_espresso_thousands_of_quizzes_to_learn_english_for_free_k_5b68365da052d1_6902955015335563176567() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kisspng-coffee-cup-cafe-tea-espresso-thousands-of-quizzes-to-learn-english-for-fr"& _ 
                        "ee-k-5b68365da052d1.6902955015335563176567", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property S__5963785() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S__5963785", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vector_coffee_cup_on_background_menu_for_restaurant_cafe_bar_coffeehouse_eps_vector_csp19862287__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vector-coffee-cup-on-background-menu-for-restaurant-cafe-bar-coffeehouse-eps-vect"& _ 
                        "or_csp19862287 (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vintage_background_for_coffee_menu_coffee_bean_vector_1236122() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vintage-background-for-coffee-menu-coffee-bean-vector-1236122", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
